### ISSUE TITLE
user flows article is not very relevant?

### ISSUE THREAD

**Issue by foucist** [sovesove/uxchecklist#3]
For the user flows link, I was expecting something that was more about the user flow within a multi-page website or multi-screen mobile app.  The conversion funnel discussion is only vaguely related at a very high level.

For example, how about an article about mapping user flows, and how they're different from sitemaps because there are loops and decision points?  Or something like https://www.nngroup.com/articles/wireflows/ could work.

**Comment by sovesove** [comment]
Hey, thanks for the feedback! Yes, agree there might be better articles to support that point.
The one from NNG looks a bit too specific on wires creation, what do you think about this one instead:
https://www.uxpin.com/studio/blog/creating-perfect-user-flows-for-smooth-ux/

**Comment by sovesove** [comment]
Or https://signalvnoise.com/posts/1926-a-shorthand-for-designing-ui-flows

**Comment by foucist** [comment]
I like that last one actually, since it's a usable approach right off the bat, which even non-UX designers can grasp and get playing with.
